### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by TuomLarsen** [andersk/haskell-constructible#3]
(This is not an issue, hope you don't mind filling it here.)

Hi!

Your library looks very intriguing as it packs a lot of functionality in so few lines, would you be please so kind and explain few basic concepts to me?

1. How fast is it? I mean, do you happen to know how does it compare to more general approaches for algebraic numbers (such as using bivariate resultants)? What is the expensive part of the algorithm?

2. Is there any low-level computational primitive it relies on that makes it fast or slow? I'm asking because from what I can tell https://github.com/leovt/constructible uses slightly different square root algorithm for rationals (`_try_sqrt`) which amounts to prime factorisation (`isqrt`).

3. Is it getting slower as it is used? I mean, does Construct has some kind of history (akin to expression tree) which it is building as various operations get executed? Is there any kind of simplification going on when it would possible to express the tree with fewer nodes? What makes it slower, large numbers or the operation count? Could it happen that at the end of a calculation a "relatively simple" number has complicated representation?

4. What was the motivation behind the library? Were you pondering any other approaches to constructible numbers? Do you plan to write a paper about it?

Thank you very much in advance!

**Comment by andersk** [comment]
I described the algorithm I use in [this MathOverflow post](https://mathoverflow.net/a/377201/68546). I don’t claim to have invented it; it’s a pretty straightforward idea. I had some plans to use it in an automated search tool for geometrical constructions, but I haven’t gotten around to that yet.

I haven’t attempted to benchmark this against other algorithms, but I expect it performs favorably. The only ways to make it particularly slow are either to make the underlying integers very large (Haskell integers use GMP under the hood), or to make a tall field extension by computing a number based on a lot of different square roots that don’t simplify.

I think that Python library is using the same algorithm, so I’m not sure why it’s doing anything with prime factorization. The extra work of decomposing numbers into square and squarefree parts is entirely wasted because the squarefree part is only used in a boolean test for whether it’s 1.

**Comment by andersk** [comment]
Oh, and while it is possible to build a number in such a way that its representation is more complicated than necessary:

```haskell
λ> sqrt 2+sqrt 3+sqrt 15+sqrt 35+sqrt 14-sqrt 3-sqrt 15-sqrt 35-sqrt 14 :: Construct
sqrt 2
λ> sqrt 3+sqrt 15+sqrt 35+sqrt 14+sqrt 2-sqrt 3-sqrt 15-sqrt 35-sqrt 14 :: Construct
1/105*sqrt 3*sqrt 15*sqrt 35*sqrt 14
```

I don’t expect this to happen to a huge degree in practice. But I guess you’ll have to try it out and see what happens in your application.

**Comment by TuomLarsen** [comment]
Thank you very much for the answers!

> The only ways to make it particularly slow are either to make the underlying integers very large (Haskell integers use GMP under the hood), or to make a tall field extension by computing a number based on a lot of different square roots that don’t simplify.

I believe this part is not a problem as it is inevitable. Even when computing with general algorithm for algebraic numbers the minimal polynomial (and its coefficients) simply grow (and quite fast). The difference, it seems me, and the question was that the "general" algorithm can use tools such as polynomial factorisation and canceling out the content whereas here I'm not sure what it does (or what is possible to do) to help to lower the "height" of field extension.

In the example you gave, would it be possible somehow rewrite the field extension to always make it result in √2? Or perhaps there is non-trivial chance that when using a (non-simplified) number further it might happen that it will cancel out when it will meed with the right operators and numbers? What I try to ask, if there is a number like the second example of yours, could it happen that it will simplify eventually?

Because from what I read so far (both the code and your answers) the only problem seems to be that it might travers too tall and redundant field extensions. One way to address it would be to construct a minimal polynomial out of the number, factor it, and construct a lower field extension but that seems like total overkill. Am I seeing this more or less correctly?

**Comment by andersk** [comment]
Whenever an operation is performed between two numbers *a* ∈ *F* and *b* ∈ *G* represented in different field extension chains, they need to be rewritten into a common chain by rebuilding each quadratic extension in *G* on top of *F*. Any of these extensions that already exist in *F* or the previously rebuilt extensions are discarded at this stage. Redundant extensions like ℚ[√2][√3][√6] are not allowed (those would break correctness, not just performance). So if you’re not introducing new square roots into the computation that weren’t previously reachable with field operations, the length of the chains will not increase.

This still allows two possibilities where numbers are represented suboptimally:

* A number could be represented with non-redundant extensions that are nonetheless unused by the particular number, such as √2 ∈ ℚ[√2][√3][√5][√7]. These shouldn’t have much of an impact because all-zero branches of the number’s tree representation are always collapsed to an optimized `SqrtZero` leaf node. One could go further and add a step to identify and discard the unused extensions, but the current implementation doesn’t.

  If you want to manually discard them, you can do it by round-tripping the number through `deconstruct`:

  ```haskell
  gc :: Construct -> Construct
  gc x = case deconstruct x of
    Left q -> fromRational q
    Right (a, b, r) -> gc a + gc b * sqrt (gc r)
  ```
* A number could be represented with a locally minimal chain of extensions that’s not a global minimum, such as the example above with √2 ∈ ℚ[√3][√15][√35][√14]. I’m not sure if these could be identified in a performant way.

**Comment by TuomLarsen** [comment]
Thanks again!
